name: Build and Publish Docker Image

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]

# Environment variables available to all jobs in the workflow
env:
  # The name of the Docker image you're building
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a standard Linux runner

    permissions:
      contents: read
      packages: write # Grant permission to write to GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          # GITHUB_TOKEN is a special secret automatically created by GitHub
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
